"""Core data structures and interfaces for the Rodin Frame Engine.

This module defines the fundamental building blocks of the frame system, including
the abstract `Frame` class that all frames must implement, and the `FrameContext`
TypedDict that carries state through the processing pipeline.
"""
from abc import ABC, abstractmethod
from enum import Enum
from typing import Any, Dict, List, Optional, TypedDict


class ValidationAction(Enum):
    """Defines the possible outcomes of a frame's validation slot."""
    PASS = "pass"       # The response is valid and can be sent to the user.
    FIX = "fix"         # The response has a minor issue that can be fixed programmatically.
    REVISE = "revise"   # The response is unsuitable and requires a new LLM call with feedback.
    FAIL = "fail"       # The response is unsalvageable; abort the turn.


class ValidationResult(TypedDict):
    """The structured output from a frame's `validate_output` method."""
    action: ValidationAction
    feedback: Optional[str]


class FrameContext(TypedDict):
    """A dictionary holding the complete state of a single processing turn.

    This object is created by the Frame Engine at the beginning of each turn
    and is passed sequentially through each slot of every active frame. It
    acts as the central state management and data-passing mechanism.

    Attributes:
        user_input: The raw input string from the user for the current turn.
        conversation_history: A list of all previous user/assistant messages.
        frame_memory: A persistent dict for a frame to store state across turns.
        shared_context: An ephemeral dict for frames to share data within a single turn.
        system_prompt: The system prompt to be sent to the LLM.
        llm_draft_response: The raw response generated by the LLM, before validation.
        validation_results: A dict storing the `ValidationResult` from each frame.
        repair_attempts: A counter for how many times the engine has tried to
                         revise or fix an LLM response.
    """
    user_input: str
    conversation_history: List[Dict[str, Any]]
    frame_memory: Dict[str, Any]
    shared_context: Dict[str, Any]
    system_prompt: str
    llm_draft_response: str
    validation_results: Dict[str, ValidationResult]
    repair_attempts: int


class Frame(ABC):
    """Abstract base class for all frames.

    A Frame is a modular component that encapsulates a specific AI behavior,
    policy, or interaction pattern. The Frame Engine processes a list of
    frames through the four-slot pipeline for each user turn.
    """

    def __init__(self, **kwargs: Any) -> None:
        """Initializes the frame (optional)."""
        pass

    @property
    @abstractmethod
    def name(self) -> str:
        """A unique, snake_case identifier for the frame."""
        raise NotImplementedError

    async def analyze_input(self, context: FrameContext) -> Optional[Dict[str, Any]]:
        """Slot 1: Analyzes user input and updates context before prompt shaping.

        Args:
            context: The current turn's `FrameContext`.

        Returns:
            An optional dictionary of findings to be placed in `shared_context`.
        """
        return None

    async def shape_prompt(self, context: FrameContext) -> str:
        """Slot 2: Modifies the system prompt before it is sent to the LLM.

        Args:
            context: The current turn's `FrameContext`.

        Returns:
            The modified system prompt.
        """
        return context["system_prompt"]

    async def validate_output(self, context: FrameContext) -> ValidationResult:
        """Slot 3: Validates the LLM's draft response against the frame's rules.

        Args:
            context: The current turn's `FrameContext`, including the
                     `llm_draft_response`.

        Returns:
            A `ValidationResult` object indicating how the engine should proceed.
        """
        return {"action": ValidationAction.PASS, "feedback": None}

    async def repair_output(self, context: FrameContext) -> str:
        """Slot 4: Attempts to programmatically fix a failed validation.

        This slot is only triggered if a frame's `validate_output` method
        returns `ValidationAction.FIX`.

        Args:
            context: The current turn's `FrameContext`.

        Returns:
            The repaired `llm_draft_response`.
        """
        return context["llm_draft_response"]
