"""Core data structures and interfaces for the Rodin Frame Engine.

This module defines the fundamental building blocks of the frame system, including
the abstract `Frame` class that all frames must implement, and the `FrameContext`
TypedDict that carries state through the processing pipeline.

Note: Frame-specific data models (shared context keys, enums, TypedDicts) are
defined in their respective frame modules and exported from backend.frames.
"""
from abc import ABC, abstractmethod
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Optional, TypedDict

import yaml


class ValidationAction(Enum):
    """Defines the possible outcomes of a frame's validation slot."""
    PASS = 'pass'       # The response is valid and can be sent to the user.
    FIX = 'fix'         # The response has a minor issue that can be fixed programmatically.
    REVISE = 'revise'   # The response is unsuitable and requires a new LLM call with feedback.
    FAIL = 'fail'       # The response is unsalvageable; abort the turn.


class ValidationResult(TypedDict):
    """The structured output from a frame's `validate_output` method."""
    action: ValidationAction
    feedback: Optional[str]


class PromptSection(TypedDict):
    """A labeled section to be included in the system prompt.

    Used by frames to contribute structured content to the final system prompt.
    The engine assembles all sections in order.
    """
    label: str
    content: str


class FrameContext(TypedDict):
    """A dictionary holding the complete state of a single processing turn.

    This object is created by the Frame Engine at the beginning of each turn
    and is passed sequentially through each slot of every active frame. It
    acts as the central state management and data-passing mechanism.

    Attributes:
        user_input: The raw input string from the user for the current turn.
        conversation_history: A list of all previous user/assistant messages.
        frame_memory: A persistent dict for a frame to store state across turns.
        shared_context: An ephemeral dict for frames to share data within a single turn.
        prompt_sections: A list of `PromptSection` objects contributed by frames.
        system_prompt: The final assembled system prompt (built from prompt_sections).
        llm_draft_response: The raw response generated by the LLM, before validation.
        validation_results: A dict storing the `ValidationResult` from each frame.
        repair_attempts: A counter for how many times the engine has tried to
                         revise or fix an LLM response.
    """
    user_input: str
    conversation_history: list[dict[str, Any]]
    frame_memory: dict[str, Any]
    shared_context: dict[str, Any]
    prompt_sections: list[PromptSection]
    system_prompt: str
    llm_draft_response: str
    validation_results: dict[str, ValidationResult]
    repair_attempts: int


class Frame(ABC):
    """Abstract base class for all frames.

    A Frame is a modular component that encapsulates a specific AI behavior,
    policy, or interaction pattern. The Frame Engine processes a list of
    frames through the four-slot pipeline for each user turn.

    Prompt Shaping:
        Frames can contribute to the system prompt in two ways:
        1. `get_prompt_sections()`: Return labeled sections that the engine accumulates.
           This is the preferred approach for additive contributions.
        2. `shape_prompt()`: Transform the current prompt directly.
           Use this for modifications that need to see/alter the full prompt.

        The engine calls `get_prompt_sections()` first for all frames (accumulation),
        then calls `shape_prompt()` for any final transformations.
    """

    def __init__(self, **kwargs: Any) -> None:
        """Initializes the frame (optional)."""
        pass

    @property
    @abstractmethod
    def name(self) -> str:
        """Returns a unique, snake_case identifier for the frame."""
        ...

    async def analyze_input(self, context: FrameContext) -> Optional[dict[str, Any]]:
        """Slot 1: Analyzes user input and updates context before prompt shaping.

        Args:
            context: The current turn's `FrameContext`.

        Returns:
            An optional dictionary of findings to be placed in `shared_context`.
        """
        return None

    async def get_prompt_sections(self, context: FrameContext) -> list[PromptSection]:
        """Slot 2a: Returns labeled sections to be accumulated into the system prompt.

        This is the primary method for frames to contribute to the prompt.
        Each section is labeled for debuggability and assembled in frame order.

        Args:
            context: The current turn's `FrameContext`.

        Returns:
            A list of `PromptSection` objects to be added to the prompt.
            Return an empty list if this frame does not contribute sections.
        """
        return []

    async def shape_prompt(self, context: FrameContext) -> str:
        """Slot 2b: Transforms the assembled system prompt (optional).

        Called after all frames' sections have been accumulated. Use this
        for final modifications that need access to the full prompt.

        Args:
            context: The current turn's `FrameContext` with assembled `system_prompt`.

        Returns:
            The (potentially modified) system prompt.
        """
        return context['system_prompt']

    async def validate_output(self, context: FrameContext) -> ValidationResult:
        """Slot 3: Validates the LLM's draft response against the frame's rules.

        Args:
            context: The current turn's `FrameContext`, including the
                     `llm_draft_response`.

        Returns:
            A `ValidationResult` object indicating how the engine should proceed.
        """
        return {'action': ValidationAction.PASS, 'feedback': None}

    async def repair_output(self, context: FrameContext) -> str:
        """Slot 4: Attempts to programmatically fix a failed validation.

        This slot is only triggered if a frame's `validate_output` method
        returns `ValidationAction.FIX`.

        Args:
            context: The current turn's `FrameContext`.

        Returns:
            The repaired `llm_draft_response`.
        """
        return context['llm_draft_response']


class SessionLogger:
    """A centralized logger for session events.

    This logger is owned by the FrameEngine and can be used by all frames
    to log events. It saves sessions in YAML format.
    """

    def __init__(
        self,
        session_id: str,
        output_dir: Path = Path('sessions'),
    ):
        """Initializes the SessionLogger.

        Args:
            session_id: A unique identifier for the session.
            output_dir: The directory where session files will be saved.
        """
        self.session_id = session_id
        self.output_dir = output_dir
        self.entries: list[dict[str, Any]] = []
        self.metadata: dict[str, Any] = {}

    def set_metadata(self, key: str, value: Any) -> None:
        """Sets metadata that will be included in the session file header."""
        self.metadata[key] = value

    def log(
        self,
        event: str,
        data: Optional[dict[str, Any]] = None,
    ) -> None:
        """Logs an event to the session.

        Args:
            event: A description of the event.
            data: Optional data associated with the event.
        """
        entry: dict[str, Any] = {
            'timestamp': datetime.now().isoformat(),
            'event': event,
        }
        if data:
            entry['data'] = data
        self.entries.append(entry)

    def log_slot(
        self,
        slot_name: str,
        frame_name: str,
        details: Optional[dict[str, Any]] = None,
    ) -> None:
        """Logs the execution of a frame slot.

        Args:
            slot_name: The name of the slot (e.g., 'analyze_input').
            frame_name: The name of the frame executing the slot.
            details: Optional details about the slot execution.
        """
        self.log(
            event=f'[{slot_name}] {frame_name}',
            data=details,
        )

    def log_turn(
        self,
        turn_number: int,
        speaker: str,
        user_message: str,
        assistant_response: str,
        analysis_data: Optional[dict[str, Any]] = None,
    ) -> None:
        """Logs a complete dialogue turn.

        This logs the user input and assistant response as a single turn entry.

        Args:
            turn_number: The turn number in the session.
            speaker: The name of the speaker (student).
            user_message: The user's message.
            assistant_response: The assistant's response.
            analysis_data: Optional dict with per-turn analysis from frames.
        """
        data = {
            'speaker': speaker,
            'user': user_message,
            'assistant': assistant_response,
        }
        if analysis_data:
            data['analysis'] = analysis_data

        self.log(
            event=f'Turn {turn_number}',
            data=data,
        )

    def save(
        self,
        frame_memory: Optional[dict[str, Any]] = None,
        generate_markdown_report: bool = False,
    ) -> Path:
        """Saves the session to a YAML file and optionally a Markdown report.

        Args:
            frame_memory: Optional frame memory to include in the log.
            generate_markdown_report: If True, a human-readable Markdown
                                      report will be saved alongside the YAML file.

        Returns:
            The path to the saved YAML session file.
        """
        self.output_dir.mkdir(exist_ok=True)

        # --- Part 1: Save the standard YAML log ---
        session_data = self._build_yaml_data(frame_memory)
        yaml_file_path = self.output_dir / f'session_{self.session_id}.yaml'
        with yaml_file_path.open('w', encoding='utf-8') as f:
            yaml.dump(
                session_data,
                f,
                default_flow_style=False,
                allow_unicode=True,
                sort_keys=False,
                width=120,
            )

        # --- Part 2: Optionally save the Markdown report ---
        if generate_markdown_report:
            self._save_markdown_report(session_data, frame_memory)

        return yaml_file_path

    def _build_yaml_data(
        self, frame_memory: Optional[dict[str, Any]] = None
    ) -> dict[str, Any]:
        """Constructs the dictionary for YAML serialization."""
        session_data: dict[str, Any] = {
            'session_id': self.session_id,
            'saved_at': datetime.now().isoformat(),
        }

        # Include metadata
        if self.metadata:
            session_data['metadata'] = self.metadata

        # Always include all events and frame memory
        session_data['events'] = self.entries
        if frame_memory:
            session_data['frame_memory'] = frame_memory

        return session_data

    def _save_markdown_report(
        self,
        session_data: dict[str, Any],
        frame_memory: Optional[dict[str, Any]] = None,
    ) -> None:
        """Saves a human-readable summary of the session in Markdown format."""
        md_file_path = self.output_dir / f'session_{self.session_id}.md'
        with md_file_path.open('w', encoding='utf-8') as f:
            # --- Header ---
            f.write(f"# Session Report: {self.session_id}\n\n")
            f.write(f"**Saved at:** {session_data['saved_at']}\n\n")

            # --- Participant Summary (from frame_memory) ---
            if frame_memory:
                participation = frame_memory.get('mnemonic_co_creator_marty', {}).get(
                    'participation'
                )
                if participation:
                    f.write("## Participant Summary\n\n")
                    for student, p_data in participation.items():
                        f.write(f"### {student}\n")
                        f.write(
                            f"- **Total Contributions:** {p_data.get('contribution_count', 0)}\n\n"
                        )

            # --- Metadata ---
            if self.metadata:
                f.write("## Session Details\n\n")
                for key, value in self.metadata.items():
                    f.write(f"- **{key.replace('_', ' ').title()}:** {value}\n")
                f.write("\n")

            # --- Conversation Log ---
            f.write("## Conversation Log\n\n")
            turn_events = [
                e for e in self.entries if e['event'].startswith('Turn')
            ]
            # Sort numerically by extracting turn number, not alphabetically
            for event in sorted(turn_events, key=lambda x: int(x['event'].split()[1])):
                data = event.get('data', {})
                turn_str = event['event']
                speaker = data.get('speaker', 'Unknown')
                user_msg = data.get('user', '')
                assistant_msg = data.get('assistant', '')

                f.write(f"### {turn_str}\n\n")
                f.write(f"**{speaker}:** {user_msg}\n\n")

                # Display the per-turn comprehension analysis if it exists
                # The key '_per_turn_comprehension' is a well-known key defined
                # in the comprehension_tracker frame.
                analysis = data.get('analysis', {})
                per_turn_comp = analysis.get('_per_turn_comprehension', {})
                understood = per_turn_comp.get('understood', [])
                confused = per_turn_comp.get('confused', [])

                if understood or confused:
                    f.write("    *Turn Analysis:*\n")
                    if understood:
                        f.write(f"    - *Understood:* {', '.join(understood)}\n")
                    if confused:
                        f.write(f"    - *Confused:* {', '.join(confused)}\n")
                    f.write("\n")

                f.write(f"**Marty:** {assistant_msg}\n\n")
                f.write("---\n\n")
