name=MartyArduino
version=0.1.0
author=Alexander Enoch <alexander@robotical.io>, Rob Dobson
maintainer=Alexander Enoch <alexander@robotical.io>
sentence=Control Marty the Robot over serial from an Arduino!
paragraph=Connect an Arduino to the expansion header on Marty and use this library to write programs to control Marty. Note that Marty's TX/RX pins are 3v3 only, so use a 3v3 arduino or a level shifter.
category=Device Control
url=http://robotical.io
architectures=*
includes=MartyArduino.h
depends=HardwareSerial,Stream,string